#RentAreas Config

#   Debug ( max / full / Default:normal / stop )
Debug: normal

#   MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: RentArea
  worldguard: WorldGuard
  username: root
  password: password

#   貸借エリア看板と判断するキー文字
SignSetKey: "RentArea"

#   看板クリック時のメニュータイトル
Menu: "§a無料マンション "

#   ボタン名称
RentIn: "借りる"
RentOut: "退去する"

#   最大レンタル数設定　ゼロなら無限
RentNum: 1

#   レンタル終了日数　ゼロなら無期限
RentExpired: 90

#   期限切れユーザーの告知　Permission.admin 保有者向け
Warning: true
