main: com.mycompany.rentareas.RentAreas
name: RentAreas
version: 0.4.1
description: Rental WG Area Manager plugin
author: Kumaisu
database: true
api-version: 1.14
commands:
    freerent:
        description: Player Free Rental Area List
    rent:
        description: Rental Areas Command
        default: op
        permission-message: You do not have permission.
permissions:
    rentareas.rental:
        description: Area Rental permission
        default: false
        permission-message: You do not have permission.
    rentareas.admin:
        description: Admin Command permissions
        permission-message: You do not have permission.
        default: op
    rentareas.console:
        description: Console Command permissions
        permission-message: You do not have permission.
        default: op
